[WIP] MA-86 Refactor coupon verification to return responses only in endpoint handler
BoltApp/bolt-magento2 pull request #1054
Opened 2020-11-27 23:09 UTC by njfaries

# Description
Continuation of work started in https://github.com/BoltApp/bolt-magento2/pull/949 to move error responses to the endpoints and throw exception from internal methods.

Fixes: MA-86

#changelog

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

2020-11-28 00:44 UTC, njfaries commented
The test `removeDiscount_removeGiftCard()` was failing silently before. After the changes introduced by this PR I noticed that it was never properly finishing the testing the method it was supposed to test; it was calling the `verifyCoupon` method I changed and originally returning explicitly false instead of throwing an exception. Now that `verifyCoupon` throws an exception the method under test, `removeDiscount`, was returning false from the `catch` statement when before it was just returning true. I updated the test to actually have a giftcard mock to remove.

2020-11-30 08:40 UTC, danac-gs requested changes
You should also catch the specific BoltException here https://github.com/BoltApp/bolt-magento2/blob/master/Model/Api/UpdateDiscountTrait.php#L470

2020-12-07 20:44 UTC, njfaries commented
> You should also catch the specific BoltException here https://github.com/BoltApp/bolt-magento2/blob/master/Model/Api/UpdateDiscountTrait.php#L470

I believe this should actually be more similar to the response sending that I removed, right? I think the `removeDiscount` method should throw or rethrow a `boltException` to be handled in the `UpdateCart` class, in the same way the exception thrown by `verifyCouponCode` is being handled.

2020-12-09 22:23 UTC, njfaries commented
This has recursed into quite the PR. I've been changing helper functions to not send responses but throw `BoltExcepctions` instead, and have been hunting down other uses to update them to expect the exceptions as well. Tests still have yet to be updated. I believe this is generally the right track though to be on.

2020-12-10 22:52 UTC, njfaries commented
I've been making my way through trying to narrow the scope to just what is strictly necessary for the `validate` method in `DiscountCodeValidation.php`, while making sure that any methods that now throw exceptions that are used elsewhere still have the exceptions caught. In general they should, as the overlap is with other endpoint handlers (primarily the `UpdateCart` one), which have everything wrapped up in a large try-catch. I've only had to make a few minor tweaks to unit tests, specifically just the ones testing internal methods as they changed from expecting a response to expecting an exception. The handler tests all still pass, so I believe this is sound.  I'll be going through the checkout/discount flow manually in the morning to make sure and hopefully removing the WIP tag.

2020-12-11 12:23 UTC, danac-gs commented on Test/Unit/Model/Api/UpdateDiscountTraitTest.php
> +    //     $this->assertFalse($result);
remove commented code if redundant

2020-12-11 12:23 UTC, danac-gs approved these changes
lgtm

2020-12-15 12:26 UTC, danac-gs submitted a review, later dismissed

2020-12-15 19:25 UTC, vitaliyreznikov approved these changes
LGTM

2020-12-15 19:25 UTC, vitaliyreznikov commented on Model/Api/UpdateDiscountTrait.php
> +                    throw new BoltException(
Do we need to fix indents here?

2020-12-15 20:09 UTC, njfaries commented on Model/Api/UpdateDiscountTrait.php
> +                    throw new BoltException(
Good catch, fixing

2020-12-15 20:28 UTC, vitaliyreznikov approved these changes

2020-12-15 20:31 UTC, merged