Bugfix: collect Mirasvit store credit only if the quote has used credits
BoltApp/bolt-magento2 pull request #930
Opened 2020-09-11 12:50 UTC by dumega

# Description
When creating the Bolt cart, it should collect Mirasvit store credit only if the quote has used credits.

Fixes: (link Jira ticket)

#changelog Bugfix: collect Mirasvit store credit only if the quote has used credits

# Type of change

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [x] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [x] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

2020-09-11 12:59 UTC, vitaliyreznikov approved these changes

2020-09-11 13:30 UTC, danac-gs approved these changes

2020-09-11 15:56 UTC, johnmccombs1 requested changes
@dumega  After merging your PR https://github.com/BoltApp/bolt-magento2/pull/920, I see that we’re missing the path for Payment, FrontNameResolver , Observer in the method checkMirasvitCreditAdminQuoteUsed. See here: https://prnt.sc/ufl8he
I’m thinking this will cause errors if the method checkMirasvitCreditAdminQuoteUsed is called. Can you confirm and added the fix into this PR?

2020-09-14 06:24 UTC, danac-gs approved these changes

2020-09-14 09:07 UTC, johnmccombs1 approved these changes

2020-09-15 06:11 UTC, merged