Fixing new lint issues part 1
BoltApp/bolt-magento2 pull request #941
Opened 2020-09-15 20:39 UTC by matt-thomason

# Description
Linting project didn't cover everything it seems, and we have some new linting issues. Doing one final cleanup before re-enabling phpcs job in circleci.

Part 1.

#changelog PHPCS Linting

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

2020-09-15 21:52 UTC, johnmccombs1 approved these changes

2020-09-16 01:09 UTC, dumega approved these changes

2020-09-16 07:34 UTC, danac-gs requested changes

2020-09-16 07:34 UTC, danac-gs commented on Helper/Config.php
> +     */Users/matthewthomason/Code/plugins/bolt-magento2/Api/UpdateCartInterface.php
remove

2020-09-16 13:58 UTC, matt-thomason commented on Helper/Config.php
> +     */Users/matthewthomason/Code/plugins/bolt-magento2/Api/UpdateCartInterface.php
Good catch thanks

2020-09-16 17:13 UTC, danac-gs approved these changes

2020-09-16 18:01 UTC, merged